environment:
  matrix:
    - PYTHON: "C:\\Python27"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      USE_UNSUPPORTED_CONAN_WITH_PYTHON_2: "1"
    - PYTHON: "C:\\Python35"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      USE_UNSUPPORTED_CONAN_WITH_PYTHON_2: "1"

build: false
install:
  - .ci/appveyor/install.bat
test_script:
  - .ci/appveyor/test.bat

